[build]
  publish = "."

[functions]
  directory = "netlify/functions"

# Redirects for clean URLs to ensure they have a trailing slash.
# This makes /Drone1-FT go to /Drone1-FT/
[[redirects]]
  from = "/Drone1-FT"
  to = "/Drone1-FT/"
  status = 301

[[redirects]]
  from = "/Quad1-QFD"
  to = "/Quad1-QFD/"
  status = 301

[[redirects]]
  from = "/Drone1-FT/*"
  to = "/Drone1-FT/index.html"
  status = 200

[[redirects]]
  from = "/Quad1-QFD/*"
  to = "/Quad1-QFD/index.html"
  status = 200

# Redirect root to Drone1-FT as default
[[redirects]]
  from = "/"
  to = "/Drone1-FT/"
  status = 302

# Alternative: Subdomain routing (uncomment if you want subdomains)
# [[redirects]]
#   from = "https://drone1.Fliightstream.com/*"
#   to = "/Drone1-FT/index.html"
#   status = 200
#   force = true

# [[redirects]]
#   from = "https://quad1.Fliightstream.com/*"
#   to = "/Quad1-QFD/index.html"
#   status = 200
#   force = true 